<?php
// $Id$

/**
 * @file
 * Filterable node title field & argument for Views glossary summary.
 * 
 * Also includes a default view. Overrides 'glossary' view.
 */


/**
* Implements hook_help().
*/
function views_glossary_title_help($section) {
  switch ($section) {
    case 'admin/help#views_glossary_title':
      // Return a line-break version of the module README
      return filter_filter('process', 2, NULL, file_get_contents( dirname(__FILE__) . "/README.txt") );
  }
}

function views_glossary_title_theme() {
  return array(
    'views_view_glossary_title' => array(
      'arguments' => array(
      ),
    ),
  );
}

/**
 * Implementation of hook_views_api().
 */
function views_glossary_title_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_glossary_title'),
  );
}
